apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: scan-pipelinerun
spec:
  pipelineRef:
    name: scan-pipeline

  params:
  
  - name: use-case
    value: ""

  - name: image-scan
    value: "" 

  - name: repo-scan
    value: ""  
  
