apiVersion: tekton.dev/v1alpha1

kind: Task

metadata:
  name: scan

spec:
  description: This task is for image scanning.
  
  params:
    
    - name: use-case
      type: string
      description: Input deciding the type of artifact to be scanned.
      default: ""
      
  results:
    - name: use-case-choice
      description: For carrying the user choice.
    

  steps:
    - name: use-case-step
      image: ubuntu
      script:  |
        echo "Enter I for image scanning and R for repo scanning."
        echo "You chose $(params.use-case)"
                
        
    
